export const SET_AUTH = 'SET_AUTH'
export const SET_UID = 'SET_UID'
export const SET_USERNAME = 'SET_USERNAME'
export const SET_USERS = 'SET_ALL_USERS'
export const SET_USERINFO = 'SET_USERINFO'
export const SET_FOLLOWERS = 'SET_FOLLOWERS'
export const SET_FEED = 'SET_FEED'
export const SET_WALL = 'SET_WALL'
